sudo: required
services:
  - docker
before_install:
  - docker build -t abilash/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true abilash/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'First_CICD'
  env: ' Firstcicd-env'
  bucket_name: 'elasticbeanstalk-us-east-2-267944014309'
  bucket_path: 'First_CICD'
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
